apiVersion: v1
kind: Service
metadata:
  name: {{ include "fakesmtp.fullname" . }}
  labels:
    {{- include "fakesmtp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ int .port }}
      targetPort: {{ int .targetPort }}
      {{- if .nodePort }}
      nodePort: {{ int .nodePort }}
      {{- end }}
      {{- if .protocol }}
      protocol: {{ .protocol }}
      {{- end }}
      {{- if .name }}
      name: {{ .name }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "fakesmtp.selectorLabels" . | nindent 4 }}
