logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      default-filters:
        - StripPrefix=2
      routes:
        - id: user-ms
          uri: http://localhost:9080
          predicates:
            - Path=/api/user-service/**
        - id: registration-ms
          uri: http://localhost:9081
          predicates:
            - Path=/api/registration-service/**

openapi:
  service:
    title: gateway microservice doc
    version: 1.0.0
    url: http://localhost:9090

springdoc:
  enable-native-support: true

  api-docs:
    enabled: true
    path: /api/v1/api-docs

  swagger-ui:
    enabled: true
    path: /api/v1/swagger-ui.html
    config-url: /api/v1/api-docs/swagger-config
    urls:
      - url: /api/v1/api-docs
        name: API Gateway Service
      - url: /api/user-service/api-docs
        name: User Service
      - url: /api/registration-service/api-docs
        name: Registration Service
